name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3']
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@2.29.0
      with:
        php-version: ${{ matrix.php }}

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: "~/.cache/composer"
        key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}-v2"
        restore-keys: "php-${{ matrix.php }}-composer-"

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyze --no-progress

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
